name: Newman API Tests - 50 Requests

on:
  push:
    branches:
      - api-newman-ci

  pull_request:
    branches:
      - main

jobs:
  newman-tests:
    name: Run 50 Postman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Check Newman Version
        run: newman --version

      - name: Run 50 API Tests
        run: newman run postman/poke.json
